/**
 * Catálogo DC Pães — nomes e imagens reais do cliente.
 * imageUrl aponta para arquivos em /public/products/.
 */
export type FactoryProductSeed = {
  code: string;
  name: string;
  imageUrl: string;
  externalProductCode: string;
  unit: "un";
  packUnits: 4 | 12;
};

export const FACTORY_PRODUCT_CATALOG: FactoryProductSeed[] = [
  {
    code: "PAO-HB-ESPINAFRE-10CM",
    name: "Pão HB Espinafre 10 cm (4 und)",
    imageUrl: "/products/pao-hb-espinafre-10-cm-4-und.jpg",
    externalProductCode: "DC0001",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-BATATA-DOCE-10CM",
    name: "Pão HB Batata Doce 10 cm (4 und)",
    imageUrl: "/products/pao-hb-batata-doce-10-cm-4-und.jpg",
    externalProductCode: "DC0002",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-BRIOCHE-10CM",
    name: "Pão HB Brioche 10 cm (4 und)",
    imageUrl: "/products/pao-hb-brioche-10-cm-4-und.jpg",
    externalProductCode: "DC0003",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-TRAD-GERGELIM-10CM",
    name: "Pão HB Trad. Gergelim 10 cm (4 und)",
    imageUrl: "/products/pao-hb-trad-gergelim-10-cm-4-und.jpg",
    externalProductCode: "DC0004",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-AUSTRALIANO-10CM",
    name: "Pão HB Australiano 10 cm (4 und)",
    imageUrl: "/products/pao-hb-australiano-10-cm-4-und.jpg",
    externalProductCode: "DC0005",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-BETERRABA-10CM",
    name: "Pão HB Beterraba 10 cm (4 und)",
    imageUrl: "/products/pao-hb-beterraba-10-cm-4-und.webp",
    externalProductCode: "DC0006",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-CAJUINA-10CM",
    name: "Pão HB Cajuína 10 cm (4 und)",
    imageUrl: "/products/pao-hb-cajuina-10-cm-4-und.jpg",
    externalProductCode: "DC0007",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-CENOURA-10CM",
    name: "Pão HB Cenoura 10 cm (4 und)",
    imageUrl: "/products/pao-hb-cenoura-10cm-4-und.jpg",
    externalProductCode: "DC0008",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-DAS-CINCO-10CM",
    name: "Pão HB das Cinco 10 cm (4 und)",
    imageUrl: "/products/pao-hb-das-cinco-10-cm-4-und.jpg",
    externalProductCode: "DC0009",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-INTEGRAL-10CM",
    name: "Pão HB Integral 10 cm (4 und)",
    imageUrl: "/products/pao-hb-integral-10-cm-4-und.jpg",
    externalProductCode: "DC0010",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-RUSTICO-10CM",
    name: "Pão HB Rústico 10 cm (4 und)",
    imageUrl: "/products/pao-hb-rustico-10-cm-4-und.jpg",
    externalProductCode: "DC0011",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-AUSTRALIANO-11CM",
    name: "Pão HB Australiano 11 cm (4 und)",
    imageUrl: "/products/pao-hb-australiano-11-cm-4-und.jpg",
    externalProductCode: "DC0012",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-BATATA-DOCE-11CM",
    name: "Pão HB Batata Doce 11 cm (4 und)",
    imageUrl: "/products/pao-hb-batata-doce-11cm-4-und.jpg",
    externalProductCode: "DC0013",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-BETERRABA-11CM",
    name: "Pão HB Beterraba 11 cm (4 und)",
    imageUrl: "/products/pao-hb-beterraba-11cm-4-und.webp",
    externalProductCode: "DC0014",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-BRIOCHE-11CM",
    name: "Pão HB Brioche 11 cm (4 und)",
    imageUrl: "/products/pao-hb-brioche-11-cm-4-und.webp",
    externalProductCode: "DC0015",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-CAJUINA-11CM",
    name: "Pão HB Cajuína 11 cm (4 und)",
    imageUrl: "/products/pao-hb-cajuina-11-cm-4-und.jpg",
    externalProductCode: "DC0016",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-CENOURA-11CM",
    name: "Pão HB Cenoura 11 cm (4 und)",
    imageUrl: "/products/pao-hb-cenoura-11-cm-4-und.jpg",
    externalProductCode: "DC0017",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-ESPINAFRE-11CM",
    name: "Pão HB Espinafre 11 cm (4 und)",
    imageUrl: "/products/pao-hb-espinafre-11-cm-4-und.jpg",
    externalProductCode: "DC0018",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-RUSTICO-11CM",
    name: "Pão HB Rústico 11 cm (4 und)",
    imageUrl: "/products/pao-hb-rustico-11-cm-4-und.jpg",
    externalProductCode: "DC0019",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-TRAD-GERGELIM-11CM",
    name: "Pão HB Trad. Gergelim 11 cm (4 und)",
    imageUrl: "/products/pao-hb-trad-gergelim-11cm-4-und.webp",
    externalProductCode: "DC0020",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-TRADICIONAL-11CM",
    name: "Pão HB Tradicional 11 cm (4 und)",
    imageUrl: "/products/pao-hb-tradicional-11-cm-4-und.jpg",
    externalProductCode: "DC0021",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-BATATA-DOCE-SMASH",
    name: "Pão HB Batata Doce Smash (4 und)",
    imageUrl: "/products/pao-hb-batata-doce-smash-4-und.jpg",
    externalProductCode: "DC0022",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-HB-BRIOCHE-SMASH",
    name: "Pão HB Brioche Smash (4 und)",
    imageUrl: "/products/pao-hb-brioche-smash-4-und.jpg",
    externalProductCode: "DC0023",
    unit: "un",
    packUnits: 4,
  },
  {
    code: "PAO-BISNAGUINHA-BATATA-DOCE",
    name: "Pão Bisnaguinha Batata Doce (12 und)",
    imageUrl: "/products/pao-bisnaguinha-batata-doce-12-und.jpg",
    externalProductCode: "DC0024",
    unit: "un",
    packUnits: 12,
  },
  {
    code: "PAO-MINI-HB-AUSTRALIANO",
    name: "Pão Mini HB Australiano (12 und)",
    imageUrl: "/products/pao-mini-hb-australiano-12-und.jpg",
    externalProductCode: "DC0025",
    unit: "un",
    packUnits: 12,
  },
  {
    code: "PAO-MINI-HB-BATATA-DOCE",
    name: "Pão Mini HB Batata Doce (12 und)",
    imageUrl: "/products/pao-mini-hb-batata-doce-12-und.jpg",
    externalProductCode: "DC0026",
    unit: "un",
    packUnits: 12,
  },
  {
    code: "PAO-MINI-HB-BETERRABA",
    name: "Pão Mini HB Beterraba (12 und)",
    imageUrl: "/products/pao-mini-hb-beterraba-12-und.webp",
    externalProductCode: "DC0027",
    unit: "un",
    packUnits: 12,
  },
  {
    code: "PAO-MINI-HB-BRIOCHE",
    name: "Pão Mini HB Brioche (12 und)",
    imageUrl: "/products/pao-mini-hb-brioche-12-und.jpg",
    externalProductCode: "DC0028",
    unit: "un",
    packUnits: 12,
  },
  {
    code: "PAO-MINI-HB-CENOURA",
    name: "Pão Mini HB Cenoura (12 und)",
    imageUrl: "/products/pao-mini-hb-cenoura-12-und.webp",
    externalProductCode: "DC0029",
    unit: "un",
    packUnits: 12,
  },
  {
    code: "PAO-MINI-HB-ESPINAFRE",
    name: "Pão Mini HB Espinafre (12 und)",
    imageUrl: "/products/pao-mini-hb-espinafre-12-und.webp",
    externalProductCode: "DC0030",
    unit: "un",
    packUnits: 12,
  },
  {
    code: "PAO-MINI-HB-RUSTICO",
    name: "Pão Mini HB Rústico (12 und)",
    imageUrl: "/products/pao-mini-hb-rustico-12-und.jpg",
    externalProductCode: "DC0031",
    unit: "un",
    packUnits: 12,
  },
];

/** SKUs fictícios antigos — desativados no seed. */
export const LEGACY_MOCK_PRODUCT_CODES = [
  "PAO-HAMB-90",
  "PAO-HOTDOG",
  "PAO-FORMA",
] as const;
